### PR TITLE
Main algorithm

### PR DESCRIPTION
**Pull request by AymenBida**
### Main algorithm

In this project we created two methods: 

- bubble_sort
- bubble_sort_by

Explanation of the methods is on the readme file

### CODE REVIEW

**Comment by AymenBida** [comment]
There is just one error that can't be fixed in Rubocop, it always detects a carriage return in the first line even if we don't have one

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
### Hello team :wave: 
#### You guys did great on this project. Your methods work as they should and pass all the test cases.
#### However this project cannot be approved until you fix the linter issue.  I was able to fix it on my local machine and will walk you through the steps I followed to fix it and you should follow some steps and it should be fixed.
- [ ] Follow this [link](https://github.com/microverseinc/linters-config/tree/master/ruby) to set up linter in your local evenvironment.
- [ ] Run `rubocop -a` on the terminal. If the "Layout/EndOfLine: Carriage return character detected" still persists, hit enter on the first line in your bubble_sort.rb file to move the bubble_sort method to line 2. After this run `rubocop -a` again and it should correct all the errors this time. Then you can push it to GitHub.
#### Those were the steps I followed to solve the linter issue in my local environment. When you are done you can request another review.
slack(@ebeagusamuel)

**Comment by AymenBida** [comment]
### Main algorithm

This time we solved the problem with Rubocop detecting a carriage return in the first line

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @AymenBida and @Leandro-Barretoo  , your project is approved :tada: :tada: :tada: 
You have implemented all minimum requirements for this project to mark it as complete, it doesn't need more changes, you can go ahead and merge all of the changes on base branch,

Don't forget to fill the mandatory project completion form, and see you to next project,

Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

**Pull request merged**
